fix: psycopg poetry install & virtualenv activation in docker
Without changes in pyproject.toml, when you do `poetry install` on your local machine - you'd get error like
```
RuntimeError

  Unable to find installation candidates for psycopg-binary (3.2.1)
```

Adding pyscopg to 3.2.4 in pyproject.toml fixes the version issues (or you can do `python -m pip install psycopg==3.2.3`)

When you run `docker compose up -d` - celery container does not run and fails with error like
```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "celery": executable file not found in $PATH: unknown
```

In addition to the above error which is output to the console, all the project containers (example: airbnb_listings, airbnb_policies) would exit with an error like
```
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
```

To see these errors you can execute `docker logs <container_id/container_name` (example: `docker logs airbnb_listings`)

The issue that causes both the above errors is that Dockerfile creates a virtual environments in the docker containers but does not activate it. To solve this, we add the binaries from the `app/.venv` to the PATH variable at the end. We do this in the `builder-base` so that all the subsequent stages in Docker have this change. This results in containers being able to successfully find these binaries.